controller:
  linearKp: 2
  rotationKp: 15
  controllerFrequency: 15   #[1/s]
  maxLinearSpeed: 0.5      # [m/s]
  maxAngularSpeed: 2         # [m/s]
  minLinearSpeed: 0       # [m/s]
  maxLinearAcceleration: 0.2 # [m/s^2]
  maxAngularAcceleration: 1.5
  goalDeadZone: 0.1              # [m]

semaphoreLockService: "/semaphore_server/lock_node"
semaphoreSetupService: "/semaphore_server/setup_semaphore"
cmdVelTopic: "/mobile_base/commands/velocity"
waypointZone: 0.25           # [m]

semaphoreLockedNodes:
  robotSize: 2
  robotSpeedForward: 1    # must be more that 0
