controller:
  linearKp: 1
  rotationKp: 0.9
  controllerFrequency: 10   #[1/s]
  maxLinearSpeed: 0.7         # [m/s]
  maxAngularSpeed: 2         # [m/s]
  minLinearSpeed: 0       # [m/s]
  maxLinearAcceleration: 0.1 # [m/s^2]
  maxAngularAcceleration: 0.5
  goalDeadZone: 0.1              # [m]

semaphoreService: "/semaphore_server/lock_node"
cmdVelTopic: "/mobile_base/commands/velocity"
waypointZone: 0.3           # [m]

semaphoreLockedNodes:
  robotSize: 3
  robotSpeedForward: 1    # must be more that 0
